services:
  api:
    image: simoom-api-dev
    build:
      context: .
      dockerfile: api/Dockerfile
      target: dev
    container_name: simoom-api
    env_file:
      - api/.env
    tty: true
    ports:
      - 8080:8080
    volumes:
      - .:/go/src/app
    depends_on:
      - db
  db:
    image: mysql:8.0.32
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    container_name: simoom-db
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./mysql/initdb:/docker-entrypoint-initdb.d
      - ./mysql/schema.sql:/schema.sql
      - db_data:/var/lib/mysql

volumes:
  db_data:
