services:
  api:
    image: simoom-api-dev
    build:
      context: .
      target: local
    container_name: simoom-api
    env_file: .env
    environment:
      USE_DEBUG_LOGGER: true
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - .:/go/src/myapp
    depends_on:
      - db
  db:
    image: mysql:8.0.28
    container_name: simoom-db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./infra/mysql/initdb:/docker-entrypoint-initdb.d
      - ./infra/mysql/schema.sql:/schema.sql
      - db_data:/var/lib/mysql

volumes:
  db_data:
