// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package sqlc

import (
	"database/sql"
	"time"
)

// プロジェクト
type Project struct {
	// プロジェクトID
	ID string
	// 所有するユーザのID
	UserID string
	// プロジェクト名
	Name string
	// カラー
	Color string
	// アーカイブされたか
	IsArchived bool
	// 作成日
	CreatedAt time.Time
	// 更新日
	UpdatedAt time.Time
}

// ステップ
type Step struct {
	// ステップID
	ID string
	// 所有するユーザのID
	UserID string
	// 紐づくタスクのID
	TaskID string
	// タイトル
	Title string
	// 完了日
	CompletedAt sql.NullTime
	// 作成日
	CreatedAt time.Time
	// 更新日
	UpdatedAt time.Time
}

// タグ
type Tag struct {
	// タグID
	ID string
	// 所有するユーザのID
	UserID string
	// タグ名
	Name string
	// 作成日
	CreatedAt time.Time
	// 更新日
	UpdatedAt time.Time
}

// タスク
type Task struct {
	// タスクID
	ID string
	// 所有するユーザのID
	UserID string
	// 紐づくプロジェクトのID
	ProjectID string
	// タイトル
	Title string
	// メモ
	Content string
	// 優先度（0~3の数字で指定し、3が最も優先度が高い）
	Priority uint32
	// 期日
	DueOn sql.NullTime
	// 完了日
	CompletedAt sql.NullTime
	// 作成日
	CreatedAt time.Time
	// 更新日
	UpdatedAt time.Time
}

// タスクとタグの紐づき
type TasksTag struct {
	// 紐づくタスクID
	TaskID string
	// 紐づくタグID
	TagID string
	// 作成日
	CreatedAt time.Time
}

// ユーザ
type User struct {
	// ユーザID
	ID string
	// ユーザ名
	Name string
	// メールアドレス
	Email string
	// パスワード
	Password string
	// 作成日
	CreatedAt time.Time
	// 更新日
	UpdatedAt time.Time
}
