name: Integrate infra
on:
  pull_request:
    paths:
      - .github/workflows/integrate-infra.yaml
      - "infra/terraform/**"
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  check-format:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "~> 1.8.0"
      - name: Check code format
        run: terraform fmt -check -recursive ./infra/terraform
  validation:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "~> 1.8.0"
      - name: Initialize Terraform working directory
        run: terraform -chdir=./infra/terraform init -backend=false
      - name: Validate configuration files
        run: terraform -chdir=./infra/terraform validate
