name: Integrate terraform code
on:
  pull_request:
    paths:
      - "infra/terraform/**"
jobs:
  check-style:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: hashicorp/setup-terraform@v3
      - run: terraform fmt -check -recursive
        working-directory: ./infra/terraform
