name: Integrate go application
on:
  pull_request:
    paths:
      - .github/workflows/integrate-go.yaml
      - "cli/**"
      - "cmd/**"
      - "pkg/**"
      - go.mod
      - go.sum
      - Makefile
      - staticcheck.conf
  push:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  check-style:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}
      - uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod
      - run: go install golang.org/x/tools/cmd/goimports@latest
      - run: make check-style-go
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}
      - uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod
      - run: go install honnef.co/go/tools/cmd/staticcheck@latest
      - run: make lint-go
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}
      - uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod
      - run: make test
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}
      - uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod
      - run: go build ./...
