name: Integrate api

on:
  push:
    paths:
      - api/**

defaults:
  run:
    working-directory: api

jobs:
  check-style:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version-file: ./go.mod
      - run: go install golang.org/x/tools/cmd/goimports@latest
      - run: if [ $(goimports -l . | wc -l) -gt 0 ]; then exit 1; fi
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version-file: ./go.mod
      - run: go install honnef.co/go/tools/cmd/staticcheck@latest
      - run: go vet $(go list ./... | grep -v /sqlc)
      - run: staticcheck $(go list ./... | grep -v /sqlc)
#  test:
#    runs-on: ubuntu-22.04
#    steps:
#      - uses: actions/checkout@v4
#      - uses: actions/setup-go@v4
#        with:
#          go-version-file: ./go.mod
#      - run: cp .env.example .env
#      - run: docker compose up -d db
#      - run: make test
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version-file: ./go.mod
      - run: go build ./...
