name: Integrate go application
on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - .github/workflows/integrate-go.yaml
      - "cli/**"
      - "cmd/**"
      - "pkg/**"
      - go.mod
      - go.sum
      - Makefile
      - staticcheck.conf
  push:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  check-format:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}
      - name: Set up go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod
      - name: Install goimports
        run: go install golang.org/x/tools/cmd/goimports@latest
      - name: Check code format
        run: make check-format-go
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}
      - name: Set up go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod
      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest
      - name: Run linting
        run: make lint-go
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}
      - name: Set up go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod
      - name: Run tests
        run: make test
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}
      - name: Set up go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod
      - name: Build
        run: go build ./...
