name: Integrate api schema
on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - .github/workflows/integrate-protobuf.yaml
      - "simoompb/**"
      - buf.gen.yaml
      - buf.yaml
      - Makefile
  push:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  check-format:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}
      - name: Set up buf
        uses: bufbuild/buf-setup-action@v1.28.1
      - name: Check code format
        run: make check-format-proto
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}
      - name: Set up buf
        uses: bufbuild/buf-setup-action@v1.28.1
      - name: Run linting
        run: make lint-proto
