name: Integrate api schema
on:
  pull_request:
    paths:
      - .github/workflows/integrate-api-schema.yaml
      - "simoompb/**"
      - buf.gen.yaml
      - buf.yaml
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  check-format:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Set up Buf
        uses: bufbuild/buf-setup-action@v1.28.1
        with:
          github_token: ${{ github.token }}
      - name: Check code format
        run: buf format --exit-code
  lint:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Set up Buf
        uses: bufbuild/buf-setup-action@v1.28.1
        with:
          github_token: ${{ github.token }}
      - name: Run linting
        run: buf lint
